---
title: "Home Work 5"
author: "William Trevino"
date: "June 12, 2018"
output: html_document
---

### 1)

```{r, echo=TRUE}
setwd("/Data Science/SMU/SMU-MSDS-6306/Homework/Week 5/")
df <- read.csv(file = "yob2016.txt", sep = ";", header = FALSE)
colnames(df) <- c("First_name","Gender","Count")
summary(df)
str(df)
y2016 <- df[!grepl("yyy", df$`First_name`),]
```

### 2)
```{r, echo=TRUE}
y2015 <- read.csv(file = "yob2015.txt",header = FALSE)
colnames(y2015) <- c("First_name","Gender","Count")
tail(y2015)
final <- merge(y2016, y2015, by=c("First_name")) 
any(is.na(final))
```

### 3)

```{r, echo=TRUE}
final$Total <- apply(final[,c("Count.x","Count.y")], 1, function(z) sum(z))
final <- final[order(-final$Total),]
head(final)
Girls <- final[final$Gender.x == "F",]
head(Girls)
top <- head(as.data.frame(Girls[Girls$Gender.x == "F",1]), n = 10)
colnames(top) <- c('Name')
write.csv(top, row.names = TRUE, file="girl_names.csv")
```

### 3)Github Repo

https://github.com/williamtrevino/SMU-MSDS-6306